// Multi-Language Support - Hausa, English, Arabic
const translations = {
    en: {
        appName: 'KasuwaPOS Pro',
        tagline: 'Smart Business Management',
        login: 'Login',
        register: 'Register',
        email: 'Email',
        password: 'Password',
        shopName: 'Shop Name',
        businessType: 'Business Type',
        phone: 'Phone Number',
        address: 'Address',
        dashboard: 'Dashboard',
        pos: 'Point of Sale',
        products: 'Products',
        sales: 'Sales',
        customers: 'Customers',
        reports: 'Reports',
        settings: 'Settings',
        logout: 'Logout',
        totalSales: 'Total Sales',
        todaySales: 'Today's Sales',
        totalProducts: 'Total Products',
        lowStock: 'Low Stock',
        addProduct: 'Add Product',
        productName: 'Product Name',
        price: 'Price',
        quantity: 'Quantity',
        category: 'Category',
        barcode: 'Barcode',
        save: 'Save',
        cancel: 'Cancel',
        delete: 'Delete',
        edit: 'Edit',
        search: 'Search',
        filter: 'Filter',
        date: 'Date',
        amount: 'Amount',
        payment: 'Payment',
        cash: 'Cash',
        card: 'Card',
        transfer: 'Transfer',
        customer: 'Customer',
        addCustomer: 'Add Customer',
        customerName: 'Customer Name',
        subscription: 'Subscription',
        plan: 'Plan',
        upgrade: 'Upgrade',
        currentPlan: 'Current Plan',
        expiryDate: 'Expiry Date',
        features: 'Features',
        unlimited: 'Unlimited',
        users: 'Users',
        staff: 'Staff',
        addStaff: 'Add Staff',
        role: 'Role',
        owner: 'Owner',
        manager: 'Manager',
        cashier: 'Cashier',
        language: 'Language',
        darkMode: 'Dark Mode',
        printReceipt: 'Print Receipt',
        discount: 'Discount',
        tax: 'Tax',
        subtotal: 'Subtotal',
        total: 'Total',
        pay: 'Pay',
        change: 'Change',
        receipt: 'Receipt',
        transactionId: 'Transaction ID',
        thankYou: 'Thank You!',
        visitAgain: 'Please Visit Again',
        newSale: 'New Sale',
        hold: 'Hold',
        resume: 'Resume',
        clear: 'Clear',
        item: 'Item',
        items: 'Items',
        stock: 'Stock',
        minStock: 'Min Stock',
        supplier: 'Supplier',
        cost: 'Cost Price',
        profit: 'Profit',
        salesReport: 'Sales Report',
        inventoryReport: 'Inventory Report',
        profitReport: 'Profit Report',
        daily: 'Daily',
        weekly: 'Weekly',
        monthly: 'Monthly',
        yearly: 'Yearly',
        from: 'From',
        to: 'To',
        generate: 'Generate',
        export: 'Export',
        shopSettings: 'Shop Settings',
        receiptSettings: 'Receipt Settings',
        taxRate: 'Tax Rate (%)',
        currency: 'Currency',
        receiptFooter: 'Receipt Footer',
        logo: 'Logo',
        upload: 'Upload',
        backup: 'Backup Data',
        restore: 'Restore Data',
        free: 'Free',
        basic: 'Basic',
        pro: 'Pro',
        enterprise: 'Enterprise',
        perMonth: 'per month',
        getStarted: 'Get Started',
        current: 'Current',
        maxProducts: 'Max Products',
        maxUsers: 'Max Users',
        advancedReports: 'Advanced Reports',
        customerManagement: 'Customer Management',
        apiAccess: 'API Access',
        prioritySupport: 'Priority Support',
        dedicatedSupport: 'Dedicated Support',
        choosePlan: 'Choose Your Plan',
        trial: '14-Day Free Trial',
        noCreditCard: 'No credit card required',
        secure: 'Secure & Private',
        dataIsolation: 'Your data is completely isolated from other businesses',
        encryption: 'End-to-end encryption',
        privacy: 'Privacy Guaranteed',
        multiTenant: 'Multi-Business Support',
        eachBusiness: 'Each business has its own secure workspace',
        noSharing: 'No data sharing between businesses',
        accessControl: 'Role-based access control',
        welcome: 'Welcome',
        loginToAccount: 'Login to your account',
        createAccount: 'Create your account',
        alreadyHave: 'Already have an account?',
        noAccount: 'Don't have an account?',
        forgotPassword: 'Forgot Password?',
        resetPassword: 'Reset Password',
        sendReset: 'Send Reset Link',
        backToLogin: 'Back to Login',
        success: 'Success',
        error: 'Error',
        warning: 'Warning',
        confirm: 'Confirm',
        areYouSure: 'Are you sure?',
        deleteConfirm: 'This action cannot be undone',
        yes: 'Yes',
        no: 'No',
        close: 'Close',
        loading: 'Loading...',
        noData: 'No data available',
        all: 'All',
        active: 'Active',
        inactive: 'Inactive',
        status: 'Status',
        created: 'Created',
        updated: 'Updated',
        actions: 'Actions',
        view: 'View',
        download: 'Download',
        share: 'Share',
        copy: 'Copy',
        copied: 'Copied!',
        print: 'Print',
        preview: 'Preview',
        dragDrop: 'Drag & Drop or Click to Upload',
        fileSize: 'Max file size: 5MB',
        invalidFile: 'Invalid file type',
        required: 'This field is required',
        invalidEmail: 'Invalid email address',
        passwordLength: 'Password must be at least 6 characters',
        passwordMatch: 'Passwords do not match',
        weakPassword: 'Weak password',
        strongPassword: 'Strong password',
        networkError: 'Network error. Please try again',
        sessionExpired: 'Session expired. Please login again',
        unauthorized: 'Unauthorized access',
        forbidden: 'Forbidden',
        notFound: 'Not found',
        serverError: 'Server error',
        maintenance: 'System under maintenance',
        comingSoon: 'Coming Soon',
        underConstruction: 'Under Construction',
        contactSupport: 'Contact Support',
        help: 'Help',
        faq: 'FAQ',
        terms: 'Terms of Service',
        privacyPolicy: 'Privacy Policy',
        about: 'About',
        version: 'Version',
        copyright: '© 2026 KasuwaPOS Pro. All rights reserved.'
    },
    ha: {
        appName: 'KasuwaPOS Pro',
        tagline: 'Gudanar da Kasuwanci da Wayo',
        login: 'Shiga',
        register: 'Yi Rajista',
        email: 'Imel',
        password: 'Sirri',
        shopName: 'Sunan Kasuwanci',
        businessType: 'Nau'in Kasuwanci',
        phone: 'Lambar Wayar',
        address: 'Adireshi',
        dashboard: 'Dashboard',
        pos: 'Point of Sale',
        products: 'Kaya',
        sales: 'Siyarwa',
        customers: 'Masanfa',
        reports: 'Rahotanni',
        settings: 'Saituna',
        logout: 'Fita',
        totalSales: 'Jimlar Siyarwa',
        todaySales: 'Siyarwar Yau',
        totalProducts: 'Jimlar Kaya',
        lowStock: 'Kaya da suka ƙaranci',
        addProduct: 'Ƙara Kaya',
        productName: 'Sunan Kaya',
        price: 'Farashin',
        quantity: 'Yawan',
        category: 'Rukuni',
        barcode: 'Barcode',
        save: 'Ajiye',
        cancel: 'Soke',
        delete: 'Share',
        edit: 'Gyara',
        search: 'Nema',
        filter: 'Tace',
        date: 'Kwanan Wata',
        amount: 'Adadin Kuɗi',
        payment: 'Biyan Kuɗi',
        cash: 'Kuɗi a hannu',
        card: 'Kati',
        transfer: 'Canja Wuri',
        customer: 'Masanfi',
        addCustomer: 'Ƙara Masanfi',
        customerName: 'Sunan Masanfi',
        subscription: 'Biyan Kuɗi',
        plan: 'Tsari',
        upgrade: 'Ƙara Matsayi',
        currentPlan: 'Tsarin Yanzu',
        expiryDate: 'Ranar Ƙarewa',
        features: 'Siffofi',
        unlimited: 'Marar iyaka',
        users: 'Masu Amfani',
        staff: 'Ma'aikata',
        addStaff: 'Ƙara Ma'aikaci',
        role: 'Matsayi',
        owner: 'Mallami',
        manager: 'Manaja',
        cashier: 'Mai Karɓar Kuɗi',
        language: 'Harshe',
        darkMode: 'Yanayin Duhu',
        printReceipt: 'Buga Rasiti',
        discount: 'Rangwame',
        tax: 'Haraji',
        subtotal: 'Jimla',
        total: 'Jimlar Duka',
        pay: 'Biya',
        change: 'Sauyi',
        receipt: 'Rasiti',
        transactionId: 'Lambar Ma'amala',
        thankYou: 'Na gode!',
        visitAgain: 'Da fatan za ku dawo',
        newSale: 'Siyarwa Sabo',
        hold: 'Dakata',
        resume: 'Ci gaba',
        clear: 'Share Duka',
        item: 'Abu',
        items: 'Abubuwa',
        stock: 'Kaya a Store',
        minStock: 'Mafi ƙarancin Kaya',
        supplier: 'Mai Sayarwa',
        cost: 'Farashin Sayen',
        profit: 'Ribar',
        salesReport: 'Rahoton Siyarwa',
        inventoryReport: 'Rahoton Kaya',
        profitReport: 'Rahoton Riba',
        daily: 'Kullum',
        weekly: 'Mako-mako',
        monthly: 'Wata-wata',
        yearly: 'Shekara-shekara',
        from: 'Daga',
        to: 'Zuwa',
        generate: 'Ƙirƙira',
        export: 'Fitar da',
        shopSettings: 'Saitunan Kasuwanci',
        receiptSettings: 'Saitunan Rasiti',
        taxRate: 'Kashi Haraji (%)',
        currency: 'Kuɗin Ƙasa',
        receiptFooter: 'Rubutun Ƙarshen Rasiti',
        logo: 'Tambari',
        upload: 'Loda',
        backup: 'Ajiye Bayanai',
        restore: 'Dawo da Bayanai',
        free: 'Kyauta',
        basic: 'Na Gida',
        pro: 'Na Musamman',
        enterprise: 'Kamfanoni',
        perMonth: 'kowane wata',
        getStarted: 'Fara Yanzu',
        current: 'Na Yanzu',
        maxProducts: 'Iyakar Kaya',
        maxUsers: 'Iyakar Masu Amfani',
        advancedReports: 'Rahotanni na Musamman',
        customerManagement: 'Gudanar da Masanfa',
        apiAccess: 'Samun API',
        prioritySupport: 'Taimako na Farko',
        dedicatedSupport: 'Taimako na Musamman',
        choosePlan: 'Zaɓi Tsarinku',
        trial: 'Kwana 14 Kyauta',
        noCreditCard: 'Babu buƙatar kati',
        secure: 'Tsaro da Sirri',
        dataIsolation: 'Bayananku sun rabe daga wasu kasuwanni',
        encryption: 'Tsaro mai ƙarfi',
        privacy: 'Tabbacin Sirri',
        multiTenant: 'Goɗen Kasuwanni',
        eachBusiness: 'Kowane kasuwanci yana da wurin aikinsa',
        noSharing: 'Babu raba bayani tsakanin kasuwanni',
        accessControl: 'Ikon shiga bisa matsayi',
        welcome: 'Barka da zuwa',
        loginToAccount: 'Shiga cikin asusunku',
        createAccount: 'Ƙirƙiri asusunku',
        alreadyHave: 'Kuna da asusu?',
        noAccount: 'Ba ku da asusu?',
        forgotPassword: 'An manta da sirri?',
        resetPassword: 'Sake Saita Sirri',
        sendReset: 'Aika Hanyar Sake Saita',
        backToLogin: 'Koma Shiga',
        success: 'Yi Nasara',
        error: 'Kuskure',
        warning: 'Gargadi',
        confirm: 'Tabbatar',
        areYouSure: 'Shin kun tabbata?',
        deleteConfirm: 'Wannan aikin ba za a iya juyawa ba',
        yes: 'Ee',
        no: 'A'a',
        close: 'Rufe',
        loading: 'Ana Loda...',
        noData: 'Babu bayanai',
        all: 'Duka',
        active: 'Mai aiki',
        inactive: 'Mai barci',
        status: 'Matsayi',
        created: 'An ƙirƙira',
        updated: 'An sabunta',
        actions: 'Ayyuka',
        view: 'Duba',
        download: 'Zazzage',
        share: 'Raba',
        copy: 'Kwafi',
        copied: 'An kwafi!',
        print: 'Buga',
        preview: 'Duba',
        dragDrop: 'Ja ko Danna don Loda',
        fileSize: 'Matsakaicin girman fayil: 5MB',
        invalidFile: 'Nau'in fayil ba daidai ba',
        required: 'Wannan filin dole ne',
        invalidEmail: 'Imel ba daidai ba',
        passwordLength: 'Sirri dole ne ya zama haruffa 6 ko fiye',
        passwordMatch: 'Sirrin bai dace ba',
        weakPassword: 'Sirri mai rauni',
        strongPassword: 'Sirri mai ƙarfi',
        networkError: 'Kuskuren hanyar sadarwa. Sake gwadawa',
        sessionExpired: 'Zaman ya ƙare. Sake shiga',
        unauthorized: 'Shiga ba tare da izini ba',
        forbidden: 'An hana',
        notFound: 'Ba a samu ba',
        serverError: 'Kuskuren uwar garken',
        maintenance: 'Ana gyaran tsarin',
        comingSoon: 'Zan zo da Sauri',
        underConstruction: 'Ana Gina',
        contactSupport: 'Tuntubi Taimako',
        help: 'Taimako',
        faq: 'Tambayoyi Masu Yawan Tafi',
        terms: 'Sharuɗɗan Aiki',
        privacyPolicy: 'Manufar Sirri',
        about: 'Game da Mu',
        version: 'Sigar',
        copyright: '© 2026 KasuwaPOS Pro. Duk haƙƙoƙi suna da kariya.'
    },
    ar: {
        appName: 'KasuwaPOS Pro',
        tagline: 'إدارة الأعمال الذكية',
        login: 'تسجيل الدخول',
        register: 'إنشاء حساب',
        email: 'البريد الإلكتروني',
        password: 'كلمة المرور',
        shopName: 'اسم المتجر',
        businessType: 'نوع النشاط التجاري',
        phone: 'رقم الهاتف',
        address: 'العنوان',
        dashboard: 'لوحة التحكم',
        pos: 'نقطة البيع',
        products: 'المنتجات',
        sales: 'المبيعات',
        customers: 'العملاء',
        reports: 'التقارير',
        settings: 'الإعدادات',
        logout: 'تسجيل الخروج',
        totalSales: 'إجمالي المبيعات',
        todaySales: 'مبيعات اليوم',
        totalProducts: 'إجمالي المنتجات',
        lowStock: 'مخزون منخفض',
        addProduct: 'إضافة منتج',
        productName: 'اسم المنتج',
        price: 'السعر',
        quantity: 'الكمية',
        category: 'الفئة',
        barcode: 'الباركود',
        save: 'حفظ',
        cancel: 'إلغاء',
        delete: 'حذف',
        edit: 'تعديل',
        search: 'بحث',
        filter: 'تصفية',
        date: 'التاريخ',
        amount: 'المبلغ',
        payment: 'الدفع',
        cash: 'نقداً',
        card: 'بطاقة',
        transfer: 'تحويل',
        customer: 'العميل',
        addCustomer: 'إضافة عميل',
        customerName: 'اسم العميل',
        subscription: 'الاشتراك',
        plan: 'الخطة',
        upgrade: 'ترقية',
        currentPlan: 'الخطة الحالية',
        expiryDate: 'تاريخ الانتهاء',
        features: 'المميزات',
        unlimited: 'غير محدود',
        users: 'المستخدمين',
        staff: 'الموظفين',
        addStaff: 'إضافة موظف',
        role: 'الدور',
        owner: 'المالك',
        manager: 'المدير',
        cashier: 'أمين الصندوق',
        language: 'اللغة',
        darkMode: 'الوضع الداكن',
        printReceipt: 'طباعة الإيصال',
        discount: 'الخصم',
        tax: 'الضريبة',
        subtotal: 'المجموع الفرعي',
        total: 'الإجمالي',
        pay: 'دفع',
        change: 'الباقي',
        receipt: 'إيصال',
        transactionId: 'رقم المعاملة',
        thankYou: 'شكراً لك!',
        visitAgain: 'نرجو زيارتكم مرة أخرى',
        newSale: 'بيع جديد',
        hold: 'تعليق',
        resume: 'استئناف',
        clear: 'مسح الكل',
        item: 'صنف',
        items: 'أصناف',
        stock: 'المخزون',
        minStock: 'الحد الأدنى',
        supplier: 'المورد',
        cost: 'سعر التكلفة',
        profit: 'الربح',
        salesReport: 'تقرير المبيعات',
        inventoryReport: 'تقرير المخزون',
        profitReport: 'تقرير الأرباح',
        daily: 'يومي',
        weekly: 'أسبوعي',
        monthly: 'شهري',
        yearly: 'سنوي',
        from: 'من',
        to: 'إلى',
        generate: 'إنشاء',
        export: 'تصدير',
        shopSettings: 'إعدادات المتجر',
        receiptSettings: 'إعدادات الإيصال',
        taxRate: 'نسبة الضريبة (%)',
        currency: 'العملة',
        receiptFooter: 'تذييل الإيصال',
        logo: 'الشعار',
        upload: 'رفع',
        backup: 'نسخ احتياطي',
        restore: 'استعادة',
        free: 'مجاني',
        basic: 'أساسي',
        pro: 'احترافي',
        enterprise: 'مؤسسي',
        perMonth: 'شهرياً',
        getStarted: 'ابدأ الآن',
        current: 'الحالي',
        maxProducts: 'الحد الأقصى للمنتجات',
        maxUsers: 'الحد الأقصى للمستخدمين',
        advancedReports: 'تقارير متقدمة',
        customerManagement: 'إدارة العملاء',
        apiAccess: 'الوصول API',
        prioritySupport: 'دعم أولوي',
        dedicatedSupport: 'دعم مخصص',
        choosePlan: 'اختر خطتك',
        trial: 'تجربة مجانية 14 يوم',
        noCreditCard: 'لا حاجة لبطاقة ائتمان',
        secure: 'آمن وخاص',
        dataIsolation: 'بياناتك معزولة تماماً عن المتاجر الأخرى',
        encryption: 'تشفير شامل',
        privacy: 'ضمان الخصوصية',
        multiTenant: 'دعم متعدد المتاجر',
        eachBusiness: 'كل متجر لديه مساحة عمل آمنة خاصة به',
        noSharing: 'لا يوجد مشاركة بيانات بين المتاجر',
        accessControl: 'التحكم في الوصول حسب الأدوار',
        welcome: 'مرحباً',
        loginToAccount: 'تسجيل الدخول إلى حسابك',
        createAccount: 'إنشاء حسابك',
        alreadyHave: 'لديك حساب؟',
        noAccount: 'ليس لديك حساب؟',
        forgotPassword: 'نسيت كلمة المرور؟',
        resetPassword: 'إعادة تعيين كلمة المرور',
        sendReset: 'إرسال رابط إعادة التعيين',
        backToLogin: 'العودة لتسجيل الدخول',
        success: 'نجاح',
        error: 'خطأ',
        warning: 'تحذير',
        confirm: 'تأكيد',
        areYouSure: 'هل أنت متأكد؟',
        deleteConfirm: 'لا يمكن التراجع عن هذا الإجراء',
        yes: 'نعم',
        no: 'لا',
        close: 'إغلاق',
        loading: 'جاري التحميل...',
        noData: 'لا توجد بيانات',
        all: 'الكل',
        active: 'نشط',
        inactive: 'غير نشط',
        status: 'الحالة',
        created: 'تم الإنشاء',
        updated: 'تم التحديث',
        actions: 'إجراءات',
        view: 'عرض',
        download: 'تحميل',
        share: 'مشاركة',
        copy: 'نسخ',
        copied: 'تم النسخ!',
        print: 'طباعة',
        preview: 'معاينة',
        dragDrop: 'اسحب وأفلت أو انقر للرفع',
        fileSize: 'الحد الأقصى لحجم الملف: 5 ميجابايت',
        invalidFile: 'نوع الملف غير صالح',
        required: 'هذا الحقل مطلوب',
        invalidEmail: 'بريد إلكتروني غير صالح',
        passwordLength: 'يجب أن تكون كلمة المرور 6 أحرف على الأقل',
        passwordMatch: 'كلمتا المرور غير متطابقتين',
        weakPassword: 'كلمة مرور ضعيفة',
        strongPassword: 'كلمة مرور قوية',
        networkError: 'خطأ في الشبكة. يرجى المحاولة مرة أخرى',
        sessionExpired: 'انتهت الجلسة. يرجى تسجيل الدخول مرة أخرى',
        unauthorized: 'وصول غير مصرح به',
        forbidden: 'ممنوع',
        notFound: 'غير موجود',
        serverError: 'خطأ في الخادم',
        maintenance: 'النظام تحت الصيانة',
        comingSoon: 'قريباً',
        underConstruction: 'تحت الإنشاء',
        contactSupport: 'تواصل مع الدعم',
        help: 'مساعدة',
        faq: 'الأسئلة الشائعة',
        terms: 'شروط الخدمة',
        privacyPolicy: 'سياسة الخصوصية',
        about: 'عنّا',
        version: 'الإصدار',
        copyright: '© 2026 KasuwaPOS Pro. جميع الحقوق محفوظة.'
    }
};

// Translation helper
function t(key) {
    const lang = currentLang || 'en';
    return translations[lang]?.[key] || translations['en']?.[key] || key;
}

// Set language
function setLanguage(lang) {
    currentLang = lang;
    localStorage.setItem('pos_language', lang);
    document.documentElement.lang = lang;
    document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
    updatePageLanguage();
}

// Update all elements with data-i18n attribute
function updatePageLanguage() {
    document.querySelectorAll('[data-i18n]').forEach(el => {
        const key = el.getAttribute('data-i18n');
        if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
            el.placeholder = t(key);
        } else {
            el.textContent = t(key);
        }
    });

    document.querySelectorAll('[data-i18n-title]').forEach(el => {
        const key = el.getAttribute('data-i18n-title');
        el.title = t(key);
    });
}

// Initialize language
document.addEventListener('DOMContentLoaded', () => {
    setLanguage(currentLang);
});
